import { GoogleGenAI } from "@google/genai";

const API_KEY = process.env.API_KEY || '';

// Initialize the client
const ai = new GoogleGenAI({ apiKey: API_KEY });

/**
 * Calls the Gemini API to remove watermarks.
 * It sends the original image and a mask image (generated from strokes).
 */
export const removeWatermark = async (
  originalImageBase64: string,
  maskImageBase64: string
): Promise<string> => {
  if (!API_KEY) {
    throw new Error("API Key is missing. Please set process.env.API_KEY.");
  }

  try {
    // We strip the data:image/png;base64, prefix if present
    const cleanOriginal = originalImageBase64.replace(/^data:image\/\w+;base64,/, "");
    const cleanMask = maskImageBase64.replace(/^data:image\/\w+;base64,/, "");

    const model = 'gemini-2.5-flash-image'; 

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            text: "You are an expert image editor. The first image provided is the original image. The second image is a mask where white pixels indicate the area containing a watermark or unwanted object. Your task is to remove the watermark/object specified by the mask from the original image and fill in the missing area seamlessly to match the surrounding background. Output ONLY the processed image."
          },
          {
            inlineData: {
              mimeType: "image/png",
              data: cleanOriginal,
            },
          },
          {
            inlineData: {
              mimeType: "image/png",
              data: cleanMask,
            },
          },
        ],
      },
    });

    // Extract the image from the response
    // The model typically returns text + image or just image. We look for inlineData.
    if (response.candidates && response.candidates.length > 0) {
       const parts = response.candidates[0].content.parts;
       for (const part of parts) {
         if (part.inlineData && part.inlineData.data) {
           return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
         }
       }
    }

    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
